### ISSUE TITLE
Android Studio  can't import this lib

### ISSUE THREAD

**Issue by whynogo** [jaydeepw/poly-picker#14]
Hi, 
    I really like your great job of this lib , when I try to import the lib to Android Studio(0.8.11) which does show import successfully, but I can't access ImagePickerActivity in code anyway. Then I try to import aar file directly, it does not work ,too. Any hint on that? 

Thanks.

**Comment by sunil08** [comment]
Hello sir,
Thanks for posting this awesome library.
I am new to android studio i don't know hot to import this library into my project. While adding it shows "Configuration to name 'default not found.'"

Please guide me to import this library into project.
which folder should i copy polypicker or polypickerdemo and where.

**Comment by jaydeepw** [comment]
@sunil08 You dont have to copy any folder. Just add gradle dependecny to you build.gradle file and you shall be ready to use this library right away.

**Comment by sunil08** [comment]
Thanks for help. I did all as told and project was ready to launch.
But on clicking any button on main activity crashes the application.Before that an error was thrown.

On installing project...

E/Trace﹕ error opening trace file: No such file or directory (2)

After Button click....

com.example.sunil.pickimg E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.sunil.pickimg/nl.changer.polypicker.ImagePickerActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2211)
            at android.app.ActivityThread.access$600(ActivityThread.java:149)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1300)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:153)
            at android.app.ActivityThread.main(ActivityThread.java:4987)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at nl.changer.polypicker.ImagePickerActivity.setupActionBar(ImagePickerActivity.java:104)
            at nl.changer.polypicker.ImagePickerActivity.onCreate(ImagePickerActivity.java:83)
            at android.app.Activity.performCreate(Activity.java:5020)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2211)
            at android.app.ActivityThread.access$600(ActivityThread.java:149)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1300)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:153)
            at android.app.ActivityThread.main(ActivityThread.java:4987)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by jaydeepw** [comment]
Refer to my comment on this issue
https://github.com/jaydeepw/poly-picker/issues/28

**Comment by sunil08** [comment]
Thankyou sir the project is running but in the main activity ..
Parcelable[] parcelableUris = intent.getParcelableArrayExtra(ImagePickerActivity.EXTRA_IMAGE_URIS);
* *parcelableUris  is getting null and
if(parcelableUris ==null) {
                    Log.e("Uris",""+i);  // prints i when null
                    return;
                }

**Comment by jaydeepw** [comment]
Thats really weird. Can you help me reproduce this issue?

**Comment by sunil08** [comment]
i think sending uri from ImagePickerActivity into arraylist would be better option.

**Comment by jaydeepw** [comment]
Yes, true. I have forked this project from another similar one. I could not manage to simplify that part last time when I worked on it. Maybe you should provide a PR with something like that?

**Comment by vishalwt** [comment]
Hello, my app is crash in marshmallow,poly picker  not working in marshmallow ,how can i resolve this please help me it is possible or not?
