### ISSUE TITLE
"Preview mode must have started before you can take a picture" error I9300

### ISSUE THREAD

**Issue by VincentdeWit94** [jaydeepw/poly-picker#68]
When I try to make a picture on my Galaxy S3 (I9300) I get this weird error: "Preview mode must have started before you can take a picture". It only happens on my S3 and not on my OnePlus one.

Full stacktrace:
```java    java.lang.IllegalStateException: Preview mode must have started before you can take a picture
            at com.commonsware.cwac.camera.CameraView.takePicture(CameraView.java:331)
            at com.commonsware.cwac.camera.CameraFragment.takePicture(CameraFragment.java:162)
            at nl.changer.polypicker.CwacCameraFragment.takePicture(CwacCameraFragment.java:143)
            at nl.changer.polypicker.CwacCameraFragment$DemoCameraHost.onAutoFocus(CwacCameraFragment.java:272)
            at com.commonsware.cwac.camera.CameraView.onAutoFocus(CameraView.java:413)
            at android.hardware.Camera$EventHandler.handleMessage(Camera.java:831)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
            at dalvik.system.NativeStart.main(Native Method)```

**Comment by jaydeepw** [comment]
I am sick on Samsung and its android mods on their devices. Let me see what I can do for this.

**Comment by dimitrireef** [comment]
did you found a solution

**Comment by NikhilAndroidDev** [comment]
Please let me know if any solution found . Its an urgent

**Comment by DarshanShombappa** [comment]
did u guys find the solution???

**Comment by derbalii** [comment]
did you found a solution ? help plz

**Comment by Chandu1207** [comment]
Please tell me the solution, i had same issue.

**Comment by GeylaniArca** [comment]
+

**Comment by GeylaniArca** [comment]
+1
