### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by mmanishh** [jaydeepw/poly-picker#83]
Log:

java.lang.RuntimeException: startPreview failed
            at android.hardware.Camera.startPreview(Native Method)
            at com.commonsware.cwac.camera.CameraView.startPreview(CameraView.java:533)
            at com.commonsware.cwac.camera.CameraView.initPreview(CameraView.java:528)
            at com.commonsware.cwac.camera.CameraView.initPreview(CameraView.java:511)
            at com.commonsware.cwac.camera.CameraView.previewReset(CameraView.java:501)
            at com.commonsware.cwac.camera.TexturePreviewStrategy.onSurfaceTextureSizeChanged(TexturePreviewStrategy.java:51)
            at android.view.TextureView.onSizeChanged(TextureView.java:313)
            at android.view.View.setFrame(View.java:14043)
            at android.view.View.layout(View.java:13955)
            at com.commonsware.cwac.camera.CameraView.onLayout(CameraView.java:249)
            at android.view.View.layout(View.java:13957)
            at android.view.ViewGroup.layout(ViewGroup.java:4374)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:13957)
            at android.view.ViewGroup.layout(ViewGroup.java:4374)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:13957)
            at android.view.ViewGroup.layout(ViewGroup.java:4374)
            at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1626)
            at android.view.View.layout(View.java:13957)
            at android.view.ViewGroup.layout(ViewGroup.java:4374)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
            at android.view.View.layout(View.java:13957)
            at android.view.ViewGroup.layout(ViewGroup.java:4374)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:13957)
            at android.view.ViewGroup.layout(ViewGroup.java:4374)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
            at android.view.View.layout(View.java:13957)
            at android.view.ViewGroup.layout(ViewGroup.java:4374)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:13957)
            at android.view.ViewGroup.layout(ViewGroup.java:4374)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
            at android.view.View.layout(View.java:13957)
            at android.view.ViewGroup.layout(ViewGroup.java:4374)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:13957)
            at android.view.ViewGroup.layout(ViewGroup.java:4374)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2003)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1824)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4568)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
            at android.view.Choreographer.doCallbacks(Choreographer.java:555)
            at android.view.Choreographer.doFrame(Choreographer.java:525)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4961)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)
            at dalvik.system.NativeStart.main(Native Method)

Android version : 4.1.2 
Samsung s3

**Comment by jaydeepw** [comment]
Refer this https://github.com/jaydeepw/poly-picker/issues/31

**Comment by jaydeepw** [comment]
Please close this issue, if that resolves your problem.

**Comment by mmanishh** [comment]
there is no solution in that issue

**Comment by jaydeepw** [comment]
Hmm... I need time to fix it. Unless you can submit some fix and send a PR on develop.
