### ISSUE TITLE
java.lang.LinkageError

### ISSUE THREAD

**Issue by abhishek09254** [jaydeepw/poly-picker#94]
FATAL EXCEPTION: main
                                                            PID: 1088
                                                            java.lang.LinkageError: nl.changer.polypicker.CwacCameraFragment
                                                                at nl.changer.polypicker.PagerAdapter2Fragments.getItem(PagerAdapter2Fragments.java:29)
                                                                at android.support.v13.app.FragmentStatePagerAdapter.instantiateItem(FragmentStatePagerAdapter.java:109)
                                                                at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:943)
                                                                at android.support.v4.view.ViewPager.populate(ViewPager.java:1091)
                                                                at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
                                                                at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
                                                                at android.view.View.measure(View.java:18804)
                                                                at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                at android.view.View.measure(View.java:18804)
                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                at android.view.View.measure(View.java:18804)
                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                at android.view.View.measure(View.java:18804)
                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                at android.view.View.measure(View.java:18804)
                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                at android.view.View.measure(View.java:18804)
                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                                at android.view.View.measure(View.java:18804)
                                                                at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2112)
                                                                at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1228)
                                                                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1464)
                                                                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
                                                                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                at android.os.Handler.handleCallback(Handler.java:746)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:148)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by guptasanchit90dev** [comment]
Any update on this issue.

**Comment by abhishek09254** [comment]
No dude ...I don't get any solution. I changed the library that I am using.I suggest you have to use TedPicker libs for it.

**Comment by rdadkins** [comment]
I believe that this is caused by the cwac camera dependency. In API 22+, Android added / changed fragment methods which cwac had previously used (`getHost()` and `setHost()`). You can see the change [here](https://github.com/commonsguy/cwac-camera/commit/c5be4198ff9aebb2b576db20feec4aa28dfdd226) in the cwac repository. To fix this, create a fork and change the cwac dependency to 0.7.0 and modify a few methods if needed.

**Comment by adnen-chouibi** [comment]
I  resolve that, i changed(refactor) getHost() by  getCameraHost() and setHost() by setCameraHost() in com.commonsware.cwac.camera.CameraView and CameraFragment  in cwac camera because those method are used in android API 23.
Sorry for my english but the essential to share our experiences
