### ISSUE TITLE
Crash when try to capture image in Note 4

### ISSUE THREAD

**Issue by amiraelsayed** [jaydeepw/poly-picker#95]
I have the following crash while trying to capture image in some devices like Samsung note 4 

java.lang.IllegalStateException: Preview mode must have started before you can take a picture at com.commonsware.cwac.camera.CameraView.takePicture(CameraView.java:331) at com.commonsware.cwac.camera.CameraFragment.takePicture(CameraFragment.java:162) at nl.changer.polypicker.CwacCameraFragment.takePicture(CwacCameraFragment.java:141) at nl.changer.polypicker.CwacCameraFragment$DemoCameraHost.onAutoFocus(CwacCameraFragment.java:284) at com.commonsware.cwac.camera.CameraView.onAutoFocus(CameraView.java:413) at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1200) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:145) at android.app.ActivityThread.main(ActivityThread.java:6872) at java.lang.reflect.Method.invoke(Native Method) at java.lang.reflect.Method.invoke(Method.java:372) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

can any one help me please ?

**Comment by sajalsd** [comment]
I am also fetching  the same issue.

**Comment by msain51s** [comment]
Even i am also facing the same issue.please do something for this
